name: Update Natixis Funds
on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: natixis-update
  cancel-in-progress: true
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests playwright
          playwright install chromium

      - name: Run extractor
        env:
          NATIXIS_EMAIL: ${{ secrets.NATIXIS_EMAIL }}
          NATIXIS_PASSWORD: ${{ secrets.NATIXIS_PASSWORD }}
        run: |
          python script/update.py
      - name: Run build
        run: |
          python script/build.py
      - name: Run traduction
        run: |
          python script/traduction.py
      - name: Commit data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
          git add data/funds.json
          git add output/
          git add output_html/
      
          git diff --cached --quiet && exit 0
      
          git commit -m "update funds"
      
          git fetch origin main
          git rebase origin/main
      
          git push origin main

